import { useEffect, useState } from "react";

import type { ActionItem } from "../types/actions";
import { sortActions } from "../lib/actions";
import { ProvenanceBadge } from "./ProvenanceBadge";
import { RiskBadge } from "./RiskBadge";

interface ActionQueueProps {
  actions: ActionItem[];
  maxItems?: number;
}

export function ActionQueue({ actions, maxItems = 4 }: ActionQueueProps) {
  const [expanded, setExpanded] = useState(false);
  const sorted = sortActions(actions);
  const actionSignature = sorted.map((action) => `${action.priority}:${action.team}:${action.description}`).join("|");
  const visibleActions = expanded ? sorted : sorted.slice(0, maxItems);
  const hiddenCount = Math.max(0, sorted.length - visibleActions.length);

  useEffect(() => {
    setExpanded(false);
  }, [actionSignature, maxItems]);

  return (
    <section className="panel p-5">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <div className="muted-label">Recommended OCC actions</div>
          <h3 className="mt-2 panel-title">Prioritized action queue</h3>
        </div>
        <ProvenanceBadge
          provenance={{
            category: "rule_based_logic",
            label: "Rule-based logic",
            summary: "OCC actions are generated by a transparent human-in-the-loop fusion layer rather than an autonomous dispatch optimizer.",
          }}
        />
      </div>
      <div className="mt-5 space-y-3">
        {sorted.length === 0 ? (
          <div className="rounded-2xl border border-panelEdge/80 bg-slate-950/35 p-4 text-sm text-slate-300">
            No immediate action is required for the current scenario. The operator can continue monitoring the inbound
            flight state.
          </div>
        ) : null}
        {visibleActions.map((action) => (
          <div key={`${action.team}-${action.description}`} className="rounded-2xl border border-panelEdge/80 bg-slate-950/35 p-4">
            <div className="flex flex-wrap items-center justify-between gap-3">
              <div className="text-sm font-semibold text-white">{action.description}</div>
              <div className="flex items-center gap-2">
                <RiskBadge label={action.priority} />
                <RiskBadge label={action.team} tone="neutral" />
              </div>
            </div>
            <p className="mt-2 text-sm leading-6 text-slate-300">{action.rationale}</p>
          </div>
        ))}
        {hiddenCount > 0 ? (
          <button
            type="button"
            onClick={() => setExpanded(true)}
            className="rounded-full border border-panelEdge px-3 py-2 text-xs font-semibold uppercase tracking-[0.16em] text-slate-300 transition hover:border-signal.cyan/50 hover:text-white"
          >
            Show {hiddenCount} lower-priority action{hiddenCount === 1 ? "" : "s"}
          </button>
        ) : expanded && sorted.length > maxItems ? (
          <button
            type="button"
            onClick={() => setExpanded(false)}
            className="rounded-full border border-panelEdge px-3 py-2 text-xs font-semibold uppercase tracking-[0.16em] text-slate-300 transition hover:border-signal.cyan/50 hover:text-white"
          >
            Hide lower-priority actions
          </button>
        ) : null}
      </div>
    </section>
  );
}
